name: CI

on:
  push:
    branches: ['**'] # Test ALL branches
  pull_request:
    branches: ['**'] # Test ALL PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Latest LTS version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage # Single command that runs tests + generates coverage
